name: DS Batches Daily Reports

on:
  schedule:
  # Cron times are UTC
  # IST = UTC + 5:30
  # Runs every 4 hours: 00:00, 04:00, 08:00, 12:00, 16:00, 20:00 UTC
  # = 05:30, 09:30, 13:30, 17:30, 21:30, 01:30 IST

  - cron: "0 0 * * *"
  - cron: "0 4 * * *"
  - cron: "0 8 * * *"
  - cron: "0 12 * * *"
  - cron: "0 16 * * *"
  - cron: "0 20 * * *"
  workflow_dispatch: {}   # lets you trigger a run manually from the Actions tab

jobs:
  run-reports:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run all reports
        env:
          SERVICE_ACCOUNT_JSON : ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: python run_all.py
